CREATE TABLE content
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    create_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    text         TEXT,
    security_key VARCHAR(255),
    CONSTRAINT pk_content PRIMARY KEY (id)
);