CREATE TABLE translatesentence
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    create_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    text       TEXT,
    CONSTRAINT pk_translatesentence PRIMARY KEY (id)
);